server:
  port: "4443"

jwt:
  secretKey: "mima"
  expiresIn: "24h"

database:
  path: "./data/cpmail.db"

aliyun:
  accessKeyId: "LTAI5tMMtJY5Y8VRqEbiFkvh"
  accessKeySecret: "JTcvh3NUn3B0w70h2SZOgdljqdZQe6"
  bucket: "imgurl-oss"
  region: "oss-cn-chengdu"